version: "{build}"

environment:
  nodejs_version: "15"
  python_path: "C:\\Python38-x64"

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%python_path%;%python_path%\\Scripts;%PATH%
  - npm install

build_script:
  - npm run lint
  - npm run test
  - npm run create_package

artifacts:
  - path: dist\final\package\*

deploy:
  description: 'News:\n- ...'
  provider: GitHub
  auth_token:
    secure: oN14X2NG9+1O6cVQ7m2pIUkMxJ4mbZC1oht03WtJPS4E03MfPH8wZYAw9vmkSL9H
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
